name: Build
on: push
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node-canvas deps
        run: sudo apt-get install libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build --linux
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install pkg-config cairo pango libpng jpeg giflib librsvg
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
